### ISSUE TITLE
Good use of indentation and whitespace but lines are too long.

### ISSUE THREAD

**Issue by sangjunp4rk** [tripin2/prj-rev-bwfs-dasmoto#2]
I really like the use of indentation and whitespace! However, your lines are a bit long right now. Try splitting this into new lines so it's easier to read on one screen without scrolling. Convention is usually ~79-100 characters per line.

https://github.com/tripin2/dasmoto-webpage/blob/master/Dasmoto/index.html#L18

**Comment by tripin2** [comment]
Thanks, I changed this, so I hope now it is ok. I usually forget about this as my text editor is over the whole window of a large screen..
