### ISSUE TITLE
Add comments to css

### ISSUE THREAD

**Issue by sangjunp4rk** [tripin2/prj-rev-bwfs-dasmoto#4]
Try adding comments to your css page. Unlike html, css code is not naturally defined by its structure. So having comments helps you organize it and quickly navigate it. This will become very useful in the future as your code grows and your css becomes more complicated.

https://github.com/tripin2/dasmoto-webpage/blob/master/Dasmoto/resources/css/style.css#L1

**Comment by tripin2** [comment]
Okey, I will try to remember this one as I know it is really useful habit and especially with larger files it may help a lot..
