### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by sangjunp4rk** [tripin2/prj-rev-bwfs-dasmoto#5]
Good job with your code! I really like the use of whitespace and indentation! Makes your code very easy to read! Also, good decisions on the classes and ids name. It makes it very clear what its purpose is and makes grouping your sections very effective. These organizational skills come in handy as you expand your code. Finally, good decision to save images locally! Saving images adds to the stability of your website because your website is not reliant on the link to be valid all the time. Great start to the Ready program! 

I included a few notes in both the html file for you to think more critically about. First, your lines are a bit long right now. Try splitting this into new lines so it's easier to read on one screen without scrolling. Convention is usually ~79-100 characters per line. And that's about it! Great job again.

**Comment by tripin2** [comment]
Thank you very much, I hope I will do even better next time. I will try to follow the rules you outlined in your comments.
